[2025-01-09T14:28:05.868+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-09T14:28:05.882+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2025-01-09T14:28:04.533108+00:00 [queued]>
[2025-01-09T14:28:05.891+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2025-01-09T14:28:04.533108+00:00 [queued]>
[2025-01-09T14:28:05.893+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-09T14:28:05.908+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2025-01-09 14:28:04.533108+00:00
[2025-01-09T14:28:05.913+0000] {standard_task_runner.py:72} INFO - Started process 97 to run task
[2025-01-09T14:28:05.916+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extraction', 'manual__2025-01-09T14:28:04.533108+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmp2pqvg219']
[2025-01-09T14:28:05.919+0000] {standard_task_runner.py:105} INFO - Job 16: Subtask reddit_extraction
[2025-01-09T14:28:05.964+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2025-01-09T14:28:04.533108+00:00 [running]> on host cb439ca725bd
[2025-01-09T14:28:06.043+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Florent Gru' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2025-01-09T14:28:04.533108+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-09T14:28:04.533108+00:00'
[2025-01-09T14:28:06.045+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-09T14:28:06.061+0000] {logging_mixin.py:190} INFO - connected to reddit!
[2025-01-09T14:28:06.062+0000] {logging_mixin.py:190} INFO - <praw.models.listing.generator.ListingGenerator object at 0x7f2f97f28970>
[2025-01-09T14:28:06.603+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 8, in reddit_pipeline
    posts = extract_posts(instance, subreddit, time_filter, limit)
  File "/opt/airflow/etls/reddit_etl.py", line 27, in extract_posts
    for post in posts:
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/models/listing/generator.py", line 66, in __next__
    self._next_batch()
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/models/listing/generator.py", line 90, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/util/deprecate_args.py", line 46, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/reddit.py", line 731, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/reddit.py", line 514, in _objectify_request
    self.request(
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/util/deprecate_args.py", line 46, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/reddit.py", line 963, in request
    return self._core.request(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 328, in request
    return self._request_with_retries(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 234, in _request_with_retries
    response, saved_exception = self._make_request(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 186, in _make_request
    response = self._rate_limiter.call(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/rate_limit.py", line 46, in call
    kwargs["headers"] = set_header_callback()
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 282, in _set_header_callback
    self._authorizer.refresh()
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/auth.py", line 378, in refresh
    self._request_token(grant_type="client_credentials", **additional_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/auth.py", line 155, in _request_token
    response = self._authenticator._post(url=url, **data)
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/auth.py", line 59, in _post
    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 401 HTTP response
[2025-01-09T14:28:06.617+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extraction, run_id=manual__2025-01-09T14:28:04.533108+00:00, execution_date=20250109T142804, start_date=20250109T142805, end_date=20250109T142806
[2025-01-09T14:28:06.630+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-09T14:28:06.631+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 16 for task reddit_extraction (received 401 HTTP response; 97)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 8, in reddit_pipeline
    posts = extract_posts(instance, subreddit, time_filter, limit)
  File "/opt/airflow/etls/reddit_etl.py", line 27, in extract_posts
    for post in posts:
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/models/listing/generator.py", line 66, in __next__
    self._next_batch()
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/models/listing/generator.py", line 90, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/util/deprecate_args.py", line 46, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/reddit.py", line 731, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/reddit.py", line 514, in _objectify_request
    self.request(
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/util/deprecate_args.py", line 46, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/reddit.py", line 963, in request
    return self._core.request(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 328, in request
    return self._request_with_retries(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 234, in _request_with_retries
    response, saved_exception = self._make_request(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 186, in _make_request
    response = self._rate_limiter.call(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/rate_limit.py", line 46, in call
    kwargs["headers"] = set_header_callback()
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 282, in _set_header_callback
    self._authorizer.refresh()
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/auth.py", line 378, in refresh
    self._request_token(grant_type="client_credentials", **additional_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/auth.py", line 155, in _request_token
    response = self._authenticator._post(url=url, **data)
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/auth.py", line 59, in _post
    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 401 HTTP response
[2025-01-09T14:28:06.652+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-09T14:28:06.668+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-09T14:28:06.672+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
